### ISSUE TITLE
EPG not shown

### ISSUE THREAD

**Issue by lxlngr** [Raybuntu/LibreELEC.tv#1]
C2 Beta1j

I use a separate TVheadend server but EPG is not visibile in guide after reboot. 
EPG loads after stream is selected. Is this a known bug?

ps. wait for network @ 20sec does not work either

**Comment by Raybuntu** [comment]
It is not a bug. I have a similar setup and Its working for me. Reset your kodi db for epg, check your tvh server and client setup. Further talk about it on odroidforum.

**Comment by lxlngr** [comment]
Thank you for your quick reply. 
I'll check setup again. 

Verstuurd vanaf mijn iPhone
