### ISSUE TITLE
TMDB Scrapper issue

### ISSUE THREAD

**Issue by sparky2891** [Raybuntu/LibreELEC.tv#11]
I'm running rb-krypton14 and having issues with movies scrapping.

Every time I have tried for the last few days i am met with the message Unable to connect to remote server when scrapping the movie library, there doesn't seem to be anything wrong with the TMDB site it is all up and working correctly and they have verified this for me as well.
Not sure if this is purely an issue just for me or if anyone else has been experiencing it, is this a known issue at all?

**Comment by Raybuntu** [comment]
Did you update your addons?

**Comment by sparky2891** [comment]
Yes tried the updating addons approach, there is only one version available to choose from regarding the tmdb scrapper.

I have a raspberry pi 2 running openelec and that is scanning movies in correctly with no issues.

---- Radostan Riedel wrote ----


Did you update your addons?

**Comment by Raybuntu** [comment]
This addon is coming from the official kodi repo. I will check later if it's working for me.

**Comment by sparky2891** [comment]
I would like to apologise if i have wasted your time at all, but seemed to have fixed the issue for myself anyway.
I originally tried updating the add-ons including the dependencies which had no effect, however after updating and choosing the latest version listed for the following:-
The Movie Database Scraper Library 
IMDB Scraper Library 
The Movie Database

The Movie Database the versions have now updated and changed to the latest which for me is 
The Movie Database Scraper Library 2.16.0
IMDB Scraper Library 2.8.8
The Movie Database 3.9.5

I also tried the initial going into add-ons, my add-ons and then the left hand menu and check for updates.

One of these fixed it for me, so might be worth a try for anyone having a similar issue.
Not sure why they did not automatically update as it is set to do this, it seems as if to update them i had to force an update of them manually so to speak.

Thank you for your help.

**Comment by Raybuntu** [comment]
Ok thanks for confirming
