### ISSUE TITLE
Include Hyperion-NG

### ISSUE THREAD

**Issue by pienoet** [Raybuntu/LibreELEC.tv#12]
Hi Raybuntu can you pls if you have spare time compile Hyperion NG for your community build LE9/Leia?

[https://github.com/hyperion-project/hyperion.ng](url)

**Comment by pienoet** [comment]
Hi Raybuntu, any news on this?

**Comment by Raybuntu** [comment]
Unfortunately I did not start looking into it yet.

**Comment by Raybuntu** [comment]
@pienoet Would you mind testing this. It was build for my future rb-leia6 but maybe it works for you already. I have no way to test it but at least it builds. Hyperion NG is stil pre alpha and unstable so I wouldn't be surprised if it doesn't work.
[service.hyperion.ng-9.0.2.100.zip](https://github.com/Raybuntu/LibreELEC.tv/files/1263339/service.hyperion.ng-9.0.2.100.zip)

**Comment by pienoet** [comment]
Thank you raybuntu.
When i'm home from work i will test it and will report back to you.

**Comment by pienoet** [comment]
Hi Raybuntu,
I just test it and it installed fin but whe i tried to load my hyperion config i get these error:

/storage/.kodi/addons/service.hyperion.ng/bin/hyperiond: error while loading shared libraries: libdns_sd.so.1: cannot open shared object file: No such file or directory

**Comment by Raybuntu** [comment]
Thanks thats very useful. I will see if I can fix it tomorrow.

**Comment by pienoet** [comment]
Thank you!

**Comment by Raybuntu** [comment]
@pienoet Can you try this one:
[service.hyperion.ng-9.0.2.100.zip](https://github.com/Raybuntu/LibreELEC.tv/files/1266616/service.hyperion.ng-9.0.2.100.zip)

**Comment by vevsvevs** [comment]
Hello Raybuntu! Thank you for your efforts!
I've just tested it on kszaq's 8.1.6, and got this error:
`./hyperion-aml: /usr/lib/libz.so.1: version `ZLIB_1.2.9' not found (required by ./hyperion-aml)`
As i can see, 8.1.6 build has zlib 1.2.8 :(

**Comment by Raybuntu** [comment]
@vevsvevs: This is for LE 9 only

**Comment by pienoet** [comment]
@raybuntu i will test it in a bit

**Comment by pienoet** [comment]
@raybuntu the latest version works so far.
It installed fine and i can connect via the web browser...

Thank you

When wil you do a new leia build for odroid C2?

**Comment by alorbach** [comment]
Hi pienoet, 

how did you build it?
I am trying to create package.mc files for hyperion.ng, but I stuck at compiling qtbase with qtserialport addon which is required by the new hyperion.ng

**Comment by Raybuntu** [comment]
@alorbach: I have everything ready. Let me finish my rebase and clean up my commits then I will push it into my Leia branch. You can probably cherry pick for Krypton too. I've build qt-everywhere.
I'm closing the issue.
@pienoet I'm currently finishing a new leia build. I haven't checked it yet but I will publish the builds on mega.nz first for a pre release.

**Comment by vevsvevs** [comment]
@alorbach, could you please try to build NG for Krypton?

**Comment by alorbach** [comment]
I will wait for Raybuntu to finish his new leia build before trying to backport it into krypton ^^

**Comment by Raybuntu** [comment]
Should be easy to backport. Just cherry pick the commit I posted before. I will probably include it in my 8.2 Krypton builds too.

**Comment by vevsvevs** [comment]
@Raybuntu, @alorbach, thanks for your efforts, guys! I'll wait Kodi port eagerly:)

**Comment by alorbach** [comment]
I cherry picked and build hyperion.ng in my krypton branch. 
Build was successfull, but hyperion.ng fails to run with framebuffer error:

> [hyperiond FRAMEBUFFERGRABBER] <ERROR> Display opened with resolution: 1920x1080@32bit

My odroid runs on 4k resolution. Only found this thread related to this error: 
https://hyperion-project.org/threads/hyperion-ng-amlogic-grabber-on-odroid-c2.925/

Anybody else got it working?

**Comment by alorbach** [comment]
Is it possible that some files overlay with hyperion? I disabled hyperion.ng, enabled hyperion and it converted my configuration to hyperion.ng. After deinstallation, hyperion is working again.

**Comment by vevsvevs** [comment]
> [hyperiond FRAMEBUFFERGRABBER] <ERROR> Display opened with resolution: 1920x1080@32bit
Same here (K2 Pro @ kszaq's 8.1.6 LE8).

**Comment by Raybuntu** [comment]
@alorbach: Not sure but it's possible. I thought I adjusted the scripts to use a separate path.

**Comment by alorbach** [comment]
Some update, I got hyperion.ng partitially working with FullHD resolution. LED stuff works in the kodi menu. But once I start a video and amlogic grabber should start working, hyperiond crashes. 

Seems like there is still lot of work todo on the hyperion.ng side. 
What's great is the new webinterface, it will make configuring hyperion so much easier in future.

**Comment by Raybuntu** [comment]
@alorbach Can you share your patches? I might look into the rest when I find some sime.

**Comment by alorbach** [comment]
I have not patched anythign yet. I just tested with FullHD resolution (1920x1080) instead of 4k (3860x2160).

**Comment by Raybuntu** [comment]
OK I will bump hyperion.ng since there was some amlogic changes 4 days ago

**Comment by alorbach** [comment]
I will try to build with commit https://github.com/hyperion-project/hyperion.ng/commit/81f5f512577a97f4c9f01aa4a55fe63d64cfd065 during meantime

**Comment by alorbach** [comment]
Great news! https://github.com/hyperion-project/hyperion.ng/commit/81f5f512577a97f4c9f01aa4a55fe63d64cfd065 is working properly now in FullHD. I am going to test on my 4K TV later :D

**Comment by Raybuntu** [comment]
@pienoet I've pushed an update for hyperion.ng in my repo based on https://github.com/hyperion-project/hyperion.ng/commit/81f5f512577a97f4c9f01aa4a55fe63d64cfd065. Can you test that please.

**Comment by pienoet** [comment]
Yes i will test this tonight thanks!

**Comment by alorbach** [comment]
Little bit offtopic but hyperion / hyperion.ng related. This commit https://github.com/alorbach/LibreELEC.tv/commit/bf5fe6b68d9f0cfcf830066ca52261982cb95cc2 fixes an issue with x265 playback and hyperion amlgrabber.

**Comment by Raybuntu** [comment]
You can do that with tmpfiles too. I'll try to include that fix in the next hyperion addon package.

**Comment by alorbach** [comment]
There is a downside, Hyperion works fine now but HEVC Playback with 4k videos stutters. I am going to search for other solutions.

**Comment by Raybuntu** [comment]
@alorbach I've heard of that issue. Do you know if the issue affects Hyperion.NG too?

**Comment by alorbach** [comment]
Yes, because Hyperion nor Hyperion.NG work with HEVC (x265) Videos without "/sys/module/amvdec_h265/parameters/double_write_mode" set to 1. And the Video stuttering on large real 4k Videos is regardless if hyperion is running or not.

**Comment by Raybuntu** [comment]
There's nothing we can do:
https://forum.odroid.com/viewtopic.php?f=139&t=19251&start=50#p159549

**Comment by vevsvevs** [comment]
@Raybuntu , mentioned there problem is only related to HEVC content. I'm watching mainly H264-coded stuff, and unfortunately i'm still experiencing sporadic video slow-down with latest NG from @alorbach. Yesterday i've been testing it approx 6 hours in a row (was almost sure that problem solved), but still in the end - the same video issues with "stream stalled" messages :(
@alorbach , thanks again for your efforts, but my tests on several amlogic tv-boxes with different LE builds led me to the conclusion, that real problem is in the kernel. Now, thanks to you, new experience with Hyperion.NG convinced me completely, unfortunately.

**Comment by Raybuntu** [comment]
@vevsvevs and the issue doesn't happen if you watch without Hyperion? I mean for hours and hours?

**Comment by vevsvevs** [comment]
Absolutely never. For now, i'm not using Hyperion (because it unusable) on my main box, and i don't experience any described above problems.

**Comment by vevsvevs** [comment]
I've left the box switched-on for a whole day with video played, and checked log-files after that - no issue.

**Comment by pienoet** [comment]
I can confirm @vevsvevs isssue.
When disable hyperion everything is fine.
My leds are flickering and i need to buy a better psu so i can't calibrate my leds to test further.

thanks

**Comment by alorbach** [comment]
I am sure the random video stuttering problem it's related to the amlgrabber. My hope is that they will solve the problem while developing hyperion.ng.

**Comment by Raybuntu** [comment]
@alorbach: FYI https://github.com/Raybuntu/LibreELEC.tv/commit/a28a591b2f30751b57f069fdd36e60f96a0b5512

**Comment by alorbach** [comment]
I don't think this patch is a good idea because it will make watching 4k HEV Encoded movies almost impossible due the stuttering.

**Comment by Raybuntu** [comment]
I did not test it yet. But the increase of cma memory might help.
