### ISSUE TITLE
Kodi and i2c bus

### ISSUE THREAD

**Issue by saturn-hh** [Raybuntu/LibreELEC.tv#13]
This issues are explained in my post on the Odroid forum:
https://forum.odroid.com/posting.php?mode=quote&f=144&p=195765

(A debug log will follow)
- Change of settings for Libreelec not permanent (gone after next reboot)
Change of items in the main menu (If I disable them, there are back after next reboot)
- Access to Addon install from zip file not possible in the addon menu. Only after choosing "user addons" and going back one step the menu entry "install from zip" is working

- error messages in dmesg (http://paste.ubuntu.com/25038098/) 
i2c i2c-1: [aml_i2c_xfer] error ret = -5 (-EIO)
rtc-pcf8563 1-0051: pcf8563_get_datetime: read error
I don't know if these errors are relevant ?

**Comment by Raybuntu** [comment]
I have posted a rb-leia4 preview (not final release yet) over at the german kodinerds forum:
https://www.kodinerds.net/index.php/Thread/53825-LibreELEC-Krypton-Leia-Agile-Odroid-C2-Wetek-Hub-Wetek-Play-2-64bit-kernel-mit-3/?postID=391213#post391213
The rtc related dmesg spam should be gone there.
