### ISSUE TITLE
building samba ...

### ISSUE THREAD

**Issue by alorbach** [Raybuntu/LibreELEC.tv#15]
Hi,

I am trying t build your Krypton branch on a Ubuntu machine. I could build previous version without any problems. 

I am stuck now on building samba with this error: 

`[1335/2109] Compiling default/librpc/gen_ndr/ndr_dcom.c
[1336/2109] Compiling librpc/ndr/ndr_xattr.c
[1337/2109] Compiling default/librpc/gen_ndr/ndr_xattr.c
[1338/2109] Compiling librpc/ndr/ndr_negoex.c
default/librpc/gen_ndr/ndr_drsuapi.c:18:29: fatal error: ndr/compression.h: No such file or directory
 #include <ndr/compression.h>
                             ^
compilation terminated.
default/librpc/gen_ndr/ndr_dcom.c:202:22: fatal error: ndr/orpc.h: No such file or directory
 #include <ndr/orpc.h>
                      ^
compilation terminated.
Waf: Leaving directory `/home/al/git/LibreELEC.tv/build.LibreELEC-Odroid_C2.aarch64-8.2-devel/samba-4.6.6/bin'
Build failed:
 -> task failed (err #1): 
	{task: cc ndr_drsuapi.c -> ndr_drsuapi_75.o}
 -> task failed (err #1): 
	{task: cc ndr_dcom.c -> ndr_dcom_35.o}
` 

Are there any new dependencies for samba which I need to install`?

**Comment by Raybuntu** [comment]
I only do arm builds not aarch64. You should use official source code.
It looks like cross compile issues and it's probably a bug in LE.

**Comment by alorbach** [comment]
Alright I will try to build arm instead.
From the performance point of view, does it make any big difference compared to the arch64 build?

**Comment by Raybuntu** [comment]
It's the same. Memory consumption is a bit less.

**Comment by alorbach** [comment]
Thanks I am goind to build arm then.

**Comment by alorbach** [comment]
same issue with arm:
[1325/2109] Compiling default/librpc/gen_ndr/ndr_auth.c
default/librpc/gen_ndr/ndr_drsuapi.c:18:29: fatal error: ndr/compression.h: No such file or directory
 #include <ndr/compression.h>
                             ^
compilation terminated.
Waf: Leaving directory `/home/al/git/LibreELEC.tv/build.LibreELEC-Odroid_C2.arm-8.2-devel/samba-4.6.6/bin'
Build failed:  -> task failed (err #1): 
	{task: cc ndr_drsuapi.c -> ndr_drsuapi_75.o}

**Comment by alorbach** [comment]
i noticed that the headers are there with ndr_ prefix which is wired. 
You had no problems building samba with the Krypton branch?

**Comment by Raybuntu** [comment]
I always make a build after I tag it and release it. It was not a clean build though. I will build it soon again.
But I haven't changed anything with samba so if its a bug it's definitely in official LE too.
What did you change or are you just rebuilding for fun?

**Comment by alorbach** [comment]
To be honest last time I build your image it was libreelec 8.0. So many things changed since then. 
I guess it maybe something on my dev machine (Ubuntu 16.04), I can't find anything usefull on that error on google. 

Which OS are you using for building?

**Comment by Raybuntu** [comment]
Debian Jessie.

**Comment by alorbach** [comment]
I got samba build using Debian 9, so it's something related to Ubuntu 16.04.
