### ISSUE TITLE
ssh on rb-leia5

### ISSUE THREAD

**Issue by cpfaff** [Raybuntu/LibreELEC.tv#17]
He

Just flashed rb-leia5 to my odroid-c2. Seems that ssh is not enabled or not working on that build. I am not asked after fresh install if I want to enable and there is no section in the config to enable it. If it is disabled. Could you please enable it on the next build?

**Comment by Raybuntu** [comment]
It's always disabled on fresh installs. It can be enabled on the first run wizard and in the LE settings addon. However there is in Leia that the LE settings addon is disabled. You will find it in your Addons -- > All Addons
Then you can enable ssh in the settings

**Comment by cpfaff** [comment]
Nice. Thanks.
