### ISSUE TITLE
Random video stuttering on playback

### ISSUE THREAD

**Issue by alorbach** [Raybuntu/LibreELEC.tv#18]
This is proberly a libreelec issue.
I am expiriencing random video stuttering from time to time. Videoplayback suddenly slows down half speed, Audio continues. If i rewind 10 seconds, Playback resumes to normal. 

Maybe you have an idea what could cause this?

**Comment by Raybuntu** [comment]
What build are you using?
Hard to tell without logs. Could also be a network issue. Are you using hyperion?

**Comment by alorbach** [comment]
Yes I am using hyperion. 
I am using the build I had problems making in issue #16 

But I had the same problem on libreelec 8.0. 
Could it be related to hyperion? I am using it for my home made TV backlight project.

**Comment by Raybuntu** [comment]
Yes it's related to hyperion. Please see https://forum.libreelec.tv/thread/9151-hyperion-issue-playback-slowdown-and-halting/?pageNo=1
I'm closing this issue here since it's affecting official LE too and the bug is already known.
