### ISSUE TITLE
SHA256 checks fail

### ISSUE THREAD

**Issue by alorbach** [Raybuntu/LibreELEC.tv#19]
I am trying to build Leia branch and I am getting lots of download error_s due wrong sha256 hashes. 
Is this a known problem? 

Do you know any way to disable sha256 checks?

**Comment by Raybuntu** [comment]
ohhh that's bad. For me it worked well but milhouse posted lately that github changed something (don't remember) so binaries downloaded through github api don't have the same sha256. you can just remove the line PKG_SHA256. Also you can update the line. unpack script will output a line, something like:
got sha256 ...., got ....
I will close that issue cause it's a LE respectively github issue.

**Comment by alorbach** [comment]
You are right, it's more a github / LE issue. 
For now I just commented out the sha256 checks in my scripts/get, I am to lazy to remove all the wrong SHA256 values in addon package files ;).

**Comment by Raybuntu** [comment]
Should be fixed in official LE and also in my Leia branch now.
