### ISSUE TITLE
Applying patch to lirc failed

### ISSUE THREAD

**Issue by Gizmo-Ger** [Raybuntu/LibreELEC.tv#2]
While compiling from sources the process stops while building lirc.
CLEAN    lirc
      * Removing build.LibreELEC-Odroid_C2.arm-8.0-devel/lirc-0.9.4c ...
  UNPACK   lirc
      APPLY PATCH (common)   /home/shs/Raybuntu/packages/sysutils/lirc/patches/lirc-0001-always-enable-uinput.patch
patching file configure.ac
Hunk #1 FAILED at 33.
1 out of 1 hunk FAILED -- saving rejects to file configure.ac.rej
Makefile:9: die Regel für Ziel „release“ scheiterte
make: *** [release] Fehler 1

**Comment by Raybuntu** [comment]
Can you pull again. And remove the source package for lirc in sources. There was a fix in LE repo lately. upstream lirc changed their source package somehow.

**Comment by Gizmo-Ger** [comment]
Thank you - worked like a charm.

**Comment by Raybuntu** [comment]
Thanks for confirmation. Closing theissue
