### ISSUE TITLE
Rock64:rb-krypton18: ethtool throws segmentation fault

### ISSUE THREAD

**Issue by ClaudiaFrank** [Raybuntu/LibreELEC.tv#20]
Included ethtool binary throws segfault, therefore disabling tx checksum offloading by ethtool.service 
fails and gigabit is more or less unusable.

**Comment by Raybuntu** [comment]
Thanks for the submitting this issue: I tried to reproduce it and for me it's working with rb-krypton18. It's either a file corruption or there is another cause. Are you using any wifi usb dongles?

**Comment by ClaudiaFrank** [comment]
>Are you using any wifi usb dongles?
No, but I will redo the test with a clean image booted from sd card first and then booted from eMMC. 
I won't connect anything except network. Will let you know about the results.

**Comment by ClaudiaFrank** [comment]
Just for your info - it turned out that it is possible to get a layout like this
/flash is on eMMC whereas /storage is on SD. Note, I didn't configure it like this but I guess
it was in such a state as I was dd-ing an image and corrupted it. I did several tests and the only time it
happens is when you boot from SD and you need to pull off the jumper to get the eMMC recognized.
I cannot really time it but it looks like when waiting a little bit longer than three seconds to pull off the jumper it might happen that one partition from eMMC and one from SD get used.
Not LibreELEC related at all.

**Comment by Raybuntu** [comment]
Jumper method for writing an emmc seems unreliable then. I really don't understand why Pine64 don't ship with a emmc to microSD adapter like Hardkernel does. Btw C2 emmc suppose to be compatible with the ROCK64 and it ships with an adapter.
http://www.hardkernel.com/main/products/prdt_info.php?g_code=G145622510341

**Comment by ClaudiaFrank** [comment]
From what I understand, from rock64 irc channel discussions,  their ultimate goal is to have
the spi flash act like a bios to make it possible to boot from different resources
like sd, eMMC, usb, network etc... 
Would be nice if it can be done and I think it would obsolete the jumper method.
