### ISSUE TITLE
Rock64:rb-krypton18: eventlircd uses 100% cpu time

### ISSUE THREAD

**Issue by ClaudiaFrank** [Raybuntu/LibreELEC.tv#22]
Nearly every 5 second a new unix socket gets created and which points to /run/lirc/lircd.
Once 1020 sockets have been created eventlircd consumes nearly 100% cpu.
Socket creation stops at 1023 as limit is set to 1024.

**Comment by Raybuntu** [comment]
Thanks for the submitting this issue. Can you provide eventlircd journal log?
I've tried to reproduce but for me it looks fine. How can I see that a new socket is created?
However there is a bug in my builds regarding eventlircd. I need to backport a patch for uinput from 4.14 to support a missing compat ioctl. Not sure that will fix the issue.

**Comment by ClaudiaFrank** [comment]
Log will follow later. Command to see the created sockets is netstat -a | grep lircd.
if you run
watch -n5 "netstat -a | grep lircd | wc"
you will see that the first value increases by one on nearly every update.

**Comment by Raybuntu** [comment]
It does not increase in my case. It's constant at 4.

**Comment by ClaudiaFrank** [comment]
So I'm wondering if writing image to eMMC corrupted something which make ethtool and lirc not working
as expected anymore - I would vote for closing the issue for the time being. I try to understand when
and how this fails and will update on this.
Back to work for now.

**Comment by ClaudiaFrank** [comment]
Issue happens when booting up and no hdmi cable is connected. 
Once cable is connected, socket creation stops.
Every 5 second a message like this is logged, which stops also when cable gets connected.

19.708196] dwhdmi-rockchip ff3c0000.hdmi: Rate 0 missing; compute N dynamically
[   19.761101] kodi.bin[848]: unhandled level 3 translation fault (11) at 0xfffffffe, esr 0x82000007
[   19.761113] pgd = ffffffc0f5038000
[   19.761118] [fffffffe] *pgd=00000000df833003, *pud=00000000df833003, *pmd=00000000f57b8003, *pte=0000000000000000
[   19.761128] 
[   19.761136] CPU: 0 PID: 848 Comm: kodi.bin Not tainted 4.4.83 #1
[   19.761141] Hardware name: Pine64 Rock64 (DT)
[   19.761146] task: ffffffc0df918d00 task.stack: ffffffc0e394c000
[   19.761153] PC is at 0xfffffffe
[   19.761157] LR is at 0x42c618
[   19.761162] pc : [<00000000fffffffe>] lr : [<000000000042c618>] pstate: 80000030
[   19.761166] sp : 00000000fff4ae30
[   19.761170] x12: 0000000000000001 
[   19.761175] x11: 0000000000000000 x10: 00000000f70a6fb4 
[   19.761182] x9 : 0000000000000000 x8 : 0000000001960f90 
[   19.761188] x7 : 0000000000000001 x6 : 0000000001979584 
[   19.761195] x5 : 00000000019ee224 x4 : 00000000019ee224 
[   19.761202] x3 : 00000000ffffffff x2 : 0000000001979650 
[   19.761208] x1 : 00000000019ee224 x0 : 00000000019ee1e8 
[   19.761214] 

From LibreELECs point of view, I assume, it is assumed that there is a hdmi cable plugged in,
so it might be not worth investigating this issue but from general point of view I would say
it should do what it does if not hdmi cable is plugged in.

**Comment by Raybuntu** [comment]
Upps it looks like kodi is crashing and therefore restarts over and over which can explains why the socket for lircd is recreated.
It means we have 2 bugs here: kodi.service creating a socket even though it already exists and kodi crashing without hdmi connected.

**Comment by ClaudiaFrank** [comment]
I assume you are already aware of this but just to be sure, I have tested my rpi3 and it isn't behaving
like this when hdmi is disconnected. No error messages in log and no additional socket creation,
it stays at two instances.

**Comment by Raybuntu** [comment]
It's actually a kernel bug and has nothing to do with eventlircd. Socket creation comes from kodi systemd service loop. I think the issue is somewhere documented in kwiboo's issue tracker.
