### ISSUE TITLE
Rock64:rb-krypton18: usb devices do not get recognized

### ISSUE THREAD

**Issue by ClaudiaFrank** [Raybuntu/LibreELEC.tv#23]
When booting from eMMC and sd card is plugged in, no attached usb device gets recognized.
Re-plugging the usb device doesn't work.
Temporary workaround: 
Boot without sd card plugged in and once system is up and running plugin sd card.

This issue cannot be seen with other images like the xenial-minimal-image from ayufan,
so I think it must be LibreELEC specific.

**Comment by Raybuntu** [comment]
Can you please provide some logs. I don't have a emmc to reproduce myself.

**Comment by ClaudiaFrank** [comment]
I will try to see where this gets logged. First look at dmesg didn't reveal anything useful.
Did not try journalctl yet - will provide, hopefully, more infos/logs later.

**Comment by ClaudiaFrank** [comment]
After clean installation this issue cannot be replicated anymore.
