### ISSUE TITLE
Rock64:rb-krypton19: rpcbind failed on first boot

### ISSUE THREAD

**Issue by ClaudiaFrank** [Raybuntu/LibreELEC.tv#25]
During tests with clean images it was recognized that rpcbind service failed on every first boot after
LibreELEC expansion. Regardless if on SD or eMMC. 
Error was always: cannot get uid from root: no such file or directory.
One is able to start the rpcbind.service afterwards or just does another reboot which solves it as well.
So it is only an issue if one installs the image and does only the first boot and keep the rock64 running.

**Comment by Raybuntu** [comment]
It sounds to me like it could be related to this one:
https://github.com/Raybuntu/LibreELEC.tv/commit/7aaebb196808be93ebba30e3f36bb24c6a8947cb
I pre applied a pending PR from LE in my tree. I will have to investigate.

**Comment by pienoet** [comment]
This not rock64 specific,
I noticed this too on my odroid C2
