### ISSUE TITLE
RK3328: Add support for RTL8723BS wifi

### ISSUE THREAD

**Issue by mo123** [Raybuntu/LibreELEC.tv#26]
RTL8723BS wifi is currently disabled in the kernel config and also set as RTL8188 wifi as the default in the RK3328 box dts patch for Aarch64.
Not sure of what else to change to get the wifi working.
Other than that the RK3328 image I build runs well on my device.

**Comment by Raybuntu** [comment]
The config change is probably ok if it builds successfully but not sure the dts change is necessary.
