### ISSUE TITLE
Unused function in oe.py

### ISSUE THREAD

**Issue by ClaudiaFrank** [Raybuntu/LibreELEC.tv#27]
Not sure if this is the right place to post this but the function  enable_service in
service.libreelec.settings/blob/master/src/oe.py
does not make anything useful and it looks like it isn't called anyway.

```
def enable_service(service):
    try:
        if os.path.exists('%s/services/%s' % (CONFIG_CACHE, service)):
            pass
        if os.path.exists('%s/services/%s.disabled' % (CONFIG_CACHE, service)):
            pass
        service_file = '%s/services/%s' % (CONFIG_CACHE, service)
    except Exception, e:
        dbg_log('oe::enable_service', 'ERROR: (' + repr(e) + ')')
```

**Comment by Raybuntu** [comment]
Upstream code is here https://github.com/LibreELEC/service.libreelec.settings
I have nothing to do with it. Create a PR where you remove the function and Team LibreELEC will review it.
