### ISSUE TITLE
rb-leia>7 on Odroid C2: blurred h.265-videos when using hardware acceleration

### ISSUE THREAD

**Issue by flolilo** [Raybuntu/LibreELEC.tv#29]
Hello,

In rb-leia7, everything is working well for me.

However, when I update to rb-leia8 or rb-leia9, videos encoded with h.265 appear quite blurry/boxy, no matter how much (or little) the video's picture is scaled (i.e. this appears at "original" size as well as with videos that have the same resoluton as the monitor). If I switch off hardware acceleration, all is good and fine, except of course from the CPU utilisation, which will lead to "hiccups", so this is not really an option in my opinion.

This happens with local files (Samba share, GbE connection); I cannot comment on streaming services, as all those that I use seem to use h.264 (which works fine on both streams and local files). I tried several files that have resolution (from UHD to PAL) and encoders (ffmpeg & handbrake, though I know that both use x265).

If I revert my C2 back to rb-leia7, all is good and well again.

My logs don't seem to include any information that would help much with this issue; however, I would be glad to offer up as much information as I can.

**Comment by Raybuntu** [comment]
This is supposed tp be fixed in leia9 with:
https://github.com/Raybuntu/LibreELEC.tv/commit/ac48390f06dea812dee6ebd4b06c9dc04a27a67c

What does the following cmd output?
cat  /sys/module/amvdec_h265/parameters/double_write_mode

**Comment by flolilo** [comment]
```
LibreELEC:~ # cat /sys/module/amvdec_h265/parameters/double_write_mode
2
```

Would I have to update rb-leia7 -> rb-leia8 -> rb-leia9 or is rb-leia7 -> rb-leia9 sufficient (which I'd think)? Because if the latter is "enough", then I'm sorry to say that at least for me, it doesn't work. Though I could try to wipe the card and start with a fresh installation of rb-leia9 and see if that helps if you think that this is worth a try.

**Comment by Raybuntu** [comment]
OK I see busybox wasn't rebuild completely.
You can workaround with:
echo 0 >  /sys/module/amvdec_h265/parameters/double_write_mode

**Comment by alorbach** [comment]
I would recommend to go back to 0 as default for double_write_mode. It fixes that hyperion problem yes, but introduces rendering performance issues with HEVC 4k content.

**Comment by Raybuntu** [comment]
@alorbach That was the idea of the commit and it's fine in code now but my build didn't rebuild initframfs.
