### ISSUE TITLE
Cant open strm file

### ISSUE THREAD

**Issue by 146fhm** [Raybuntu/LibreELEC.tv#3]
Hi, i'm using LibreELEC-WeTek_Play_2.arm-8.0-rb-beta2b.

I use strm file to open video link but it seem didnt work. It's not even work with the youtube link. Is this a known bug?

here are the logs.
1 - http://sprunge.us/FbZY
2 - http://sprunge.us/NNdb - with debug logging

Please advise, thank you.

**Comment by Raybuntu** [comment]
What is strm?

**Comment by 146fhm** [comment]
its just the text file with the video link.

Check this out. http://kodi.wiki/view/internet_video_and_audio_streams

Thanks you.

**Comment by Raybuntu** [comment]
Can you try m3u and see if your stream play?

**Comment by 146fhm** [comment]
Ok, im trying now.

**Comment by 146fhm** [comment]
It's didnt work as well.

**Comment by 146fhm** [comment]
Here is the sample. [file.zip](https://github.com/Raybuntu/LibreELEC.tv/files/768617/file.zip)

**Comment by Raybuntu** [comment]
I have just tried an m3u from a FTA channel in Germany and all is good. What is the stream link you are using?

**Comment by 146fhm** [comment]
I had put it in the attachment file.zip above. Please take a look. 
Maybe something wrong with curl or ssl. Just guessing.
Thanks mate!

**Comment by Raybuntu** [comment]
Thats not possible. You can't just input a youtube link in a test.m3u file. No support for the other file.

**Comment by 146fhm** [comment]
Oh, really. But it's working on my Raspberry pi with LE Jarvis. Are you sure? So sorry if im wrong.

**Comment by Raybuntu** [comment]
Hmmh not sure. I have no RPi, I tried on my Debian PC with Jarvis and Krypton and I had no luck playing it.

**Comment by 146fhm** [comment]
Okay then if so, How about the other one video link anyway?

**Comment by Raybuntu** [comment]
Sorry but no support for piracy links.

**Comment by 146fhm** [comment]
Have tried with strm file to play http://www.sample-videos.com/video/mp4/720/big_buck_bunny_720p_1mb.mp4 but still no luck. Are you using WP2 as well? Thanks anyway for your quick response.

**Comment by Raybuntu** [comment]
Big Buck Bunny I can play on WP2 with rb-beta3 (haven't tried older builds). The issue with your other link might be due to ssl issues which are already known in LibreELEC.

**Comment by 146fhm** [comment]
Just tried upgraded the beta3 tar and with bick buck bunnny but still no luck. I will try with the fresh image beta3 later. Thank  you so much for your quick response.

**Comment by 146fhm** [comment]
I have tried with the latest build. It is not a problem anymore. Thank you so much for your quick response.
