### ISSUE TITLE
Not an issue

### ISSUE THREAD

**Issue by StuartIanNaylor** [Raybuntu/LibreELEC.tv#30]
Raybuntu with the chromium debate and the x11 problems would is it possible to include QT apps such as QupZilla.
https://qupzilla.com/

Seems about the best browser on linux that currently doesn't need X or Wayland.
Apols for posting the 'Browser' think but it just makes the perfect 'box' having that occasional browser thing with kodi.

**Comment by Raybuntu** [comment]
Sorry I have no time or interest to include it. Please ask at the LibreELEC Forum, if it's included in official LibreELEC I will automatically pull those changes.
