### ISSUE TITLE
libltdl/ltdl.mk: No such file or directory

### ISSUE THREAD

**Issue by alorbach** [Raybuntu/LibreELEC.tv#31]
Trying to build current Leia branch. 
Seems like some build files are missing 

> running: /home/al/git/LibreELEC.tv/build.LibreELEC-Odroid_C2.arm-9.0-devel/toolchain/bin/automake --add-missing --copy --force-missing
> automake: error: cannot open < libltdl/ltdl.mk: No such file or directory
> autoreconf: /home/al/git/LibreELEC.tv/build.LibreELEC-Odroid_C2.arm-9.0-devel/toolchain/bin/automake failed with exit status: 1
>

**Comment by Raybuntu** [comment]
You need to make a clean build.
