### ISSUE TITLE
nss - Compiling stops with fatal error

### ISSUE THREAD

**Issue by Gizmo-Ger** [Raybuntu/LibreELEC.tv#32]
For quite some time now I keep getting this compiling error.

/build.LibreELEC-Odroid_C2.arm-9.0-devel/toolchain/bin/host-gcc -o Linux4.10_x86_gcc_glibc_PTH_DBG.OBJ/nsinstall.o -c -g -fPIC -Di386 -m32 -pipe -ffunction-sections -fdata-sections -DHAVE_STRERROR -DLINUX -Dlinux -Wall -Werror -DXP_UNIX -DDEBUG -UNDEBUG -DDEBUG_shs -D_REENTRANT -DNSS_NO_INIT_SUPPORT -DUSE_UTIL_DIRECTLY -DNO_NSPR_10_SUPPORT -DSSL_DISABLE_DEPRECATED_CIPHER_SUITE_NAMES -I../../../dist/Linux4.10_x86_gcc_glibc_PTH_DBG.OBJ/include -I../../../dist/public/coreconf -I../../../dist/private/coreconf  nsinstall.c
In file included from /usr/include/stdio.h:27:0,
                 from nsinstall.c:8:
/usr/include/features.h:364:25: fatal error: sys/cdefs.h: No such file or directory
 #  include <sys/cdefs.h>
                         ^
compilation terminated.
make[1]: *** [../../coreconf/rules.mk:393: Linux4.10_x86_gcc_glibc_PTH_DBG.OBJ/nsinstall.o] Error 1
make[1]: Leaving directory '/home/shs/Raybuntu/build.LibreELEC-Odroid_C2.arm-9.0-devel/nss-3.29.5/nss/coreconf/nsinstall'
Makefile:9: die Regel für Ziel „release“ scheiterte
make: *** [release] Fehler 2

**Comment by Raybuntu** [comment]
Ahh right I remember working with Milhouse to solve that issue. I have 32bit gcc libs in my Debian and Ubuntu. I need to chery pick https://github.com/LibreELEC/LibreELEC.tv/pull/1791/commits/d36d7f6ccc01ac07cfa8d781baa767cf795728dc
You can apply that change too if you want to workaround.
