### ISSUE TITLE
Rock64:8.2-rb-krypton18: Cannot get any docker container to run

### ISSUE THREAD

**Issue by zarusz** [Raybuntu/LibreELEC.tv#33]
Hi,

I have tried LibreELEC release for ROCK64, specifically  `LibreELEC-ROCK64.arm-8.2-rb-krypton18.tar` with docker installed (via Kodi addons).  

I cannot start any docker container. I tried various architectures with no luck.

Trying to start simplest hello world container:
```
Rock64:~ #  docker run aarch64/hello-world
```

Gives the following error:
```
Unable to find image 'aarch64/hello-world:latest' locally
latest: Pulling from aarch64/hello-world
8c5c4ac25476: Pull complete
Digest: sha256:bd1722550b97668b23ede297abf824d4855f4d9f600dab7b4db1a963dae7ec9e
Status: Downloaded newer image for aarch64/hello-world:latest
container_linux.go:247: starting container process caused "process_linux.go:359: container init caused \"could not create session key: function not implemented\""
docker: Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "process_linux.go:359: container init caused \"could not create session key: function not implemented\"".
ERRO[0004] error getting events from daemon: net/http: request canceled
```

Similarly, I have tried other architectures (`docker run arm64v8/hello-world`) and containers (`docker run -it multiarch/alpine:aarch64-edge /bin/sh`) with no luck.

Previously, I have been using [Kwiboo's releases](https://github.com/Kwiboo/LibreELEC.tv/releases) and docker worked fine. However, if possible I wanted to move to Raybuntu's release as it seems to get more traction from community.

Here is my `uname -a`:
```
Linux Rock64 4.4.77 #1 SMP Wed Sep 13 15:20:04 CEST 2017 aarch64 GNU/Linux
```

**Comment by Raybuntu** [comment]
Thank you. I'm not sure what's causing the issue. I haveto admit I havent tested Rock64. I will focus on Kodi 18 in the future so I will leave that issue open until I publish a Leia testbuild.

**Comment by Raybuntu** [comment]
I have a solution. New Leia build coming soon

**Comment by zarusz** [comment]
The latest Leia build works for me now.
Thanks for sorting this out!
