### ISSUE TITLE
Build error with Krypton

### ISSUE THREAD

**Issue by alorbach** [Raybuntu/LibreELEC.tv#34]
Hi,

since a few weeks I can't build Krypton anymore. 

> 
>       APPLY PATCH (common - amlogic-3.14)   packages/linux/patches/amlogic-3.14/linux-008-fix_dvb_when_running_32bit_userspace_with_aarch64_kernel.patch
> patching file fs/compat_ioctl.c
> Hunk #2 succeeded at 1623 (offset 3 lines).
>       APPLY PATCH (common - amlogic-3.14)   packages/linux/patches/amlogic-3.14/linux-009-fix_suspend.patch
> patching file kernel/power/main.c
>       APPLY PATCH (common - amlogic-3.14)   packages/linux/patches/amlogic-3.14/linux-010-force_wakeup.patch
> patching file drivers/amlogic/cec/hdmi_ao_cec.c
> patching file drivers/amlogic/input/remote/remote_main.c
> patching file drivers/amlogic/pm/Kconfig
> patching file drivers/amlogic/pm/gxbb_pm.c
>       APPLY PATCH (common - amlogic-3.14)   packages/linux/patches/amlogic-3.14/linux-011-PR31.patch
> patching file kernel/time.c
> patching file drivers/amlogic/video_dev/Kconfig
> patching file drivers/amlogic/amports/video.c
> Reversed (or previously applied) patch detected!  Assume -R? 
> 

When I repatch the files, the image build may succeeds but the kernel fails to start video dev on startup.

**Comment by Raybuntu** [comment]
I'm about to clean up the Krypton branch. That Patch is merged upstream and it needs to be deleted.

**Comment by alorbach** [comment]
Is it save to merge current Krypton upstream branch into yours?

**Comment by Raybuntu** [comment]
I've clean it up and merged with official LE git. Not sure I pushed everything.

**Comment by alorbach** [comment]
Works, build and works (Y)
