### ISSUE TITLE
Problems when play 4k content on Rock64

### ISSUE THREAD

**Issue by mlade77** [Raybuntu/LibreELEC.tv#36]
Hello,

First of all I would like to apologize if I do not write/describe the issues I am experiencing in proper form.
I took one of these Rock64 MBs to replace my old raspberry Pi2 and with the hope of been able to watch 4k content nicely.
I downloaded several movies and some of them are being played choppily, some with strange colors in different screen regions and some normally but if I do not enable the subtitles. For these which are bing played normally when enable subtitles the movie starts to be choppily again when subtitles are displayed on screen.
I could provide some logs or other stuff you need in order problem to be located if someone tells me how and from where.

many thanks

**Comment by Raybuntu** [comment]
I'm sorry but the Rock64 is still work in progress. The Krypton build was more of an preview and my next builds will be LE9 Kodi 18 Leia based.

**Comment by mlade77** [comment]
Hello Ray,

Ok. I got this. Tell me if I can help with anything for the project. I am not a coder but sysadmin, but If I can help you with anything I will be happy to assist you.

**Comment by Raybuntu** [comment]
Thanks every help is welcome. Development is currently mostly driven by kwiboo. I currently just cherry pick from him. There are still some kernel issues and it might take a few weeks or months to solve most of it.

**Comment by mlade77** [comment]
ok. I see. Tell me what with I can help or contribute to the project?
As I said I am not a dev., but with some testing, for example I could help.

cheers

**Comment by Raybuntu** [comment]
Currently development is progressing very fast and we might have it fixed in the next few weeks if all goes according to plan.

**Comment by mlade77** [comment]
Hi Ray,

I would like to ask you about NFS boot and NFS storage mount.
I tried to do NFS storage mount on boot but I was unable to achieve it.
As far as I can see there is NFS support build into the kernel and I modified append line in extlinux.conf file with this one:
append ip=dhcp earlyprintk console=ttyFIQ0 console=tty0 boot=UUID=1309-2249 disk=NFS=192.168.x.x:/srv/rock64storage,v3,tcp ssh
Every time when my rock64 tried to boot and mount storage it failed with "unable to mount xxxxxx"
Could you give me a clue how this can be achieved?

cheers
