### ISSUE TITLE
HiFi shield

### ISSUE THREAD

**Issue by rubdos** [Raybuntu/LibreELEC.tv#37]
Hi!

It would be enormously nice to have HiFi shield support. I personally have the HiFi+ shields, and they do work on Kodi on Ubuntu.

If you don't own a HiFi shield (or have no interest in this issue), I see two options:
1) You hint me on how to accomplish this  
2) I send you a HiFi+ shield to test (and you get to keep it, fwiw).

Thanks! :-)

**Comment by Raybuntu** [comment]
Thanks but I already have one. Last time I checked it was working out of the box with my builds. Only the userspace support was missing. I had simultaneous output from HDMI and HifiShield+.

**Comment by rubdos** [comment]
Does that mean that the "official" Odroid C2 builds on LibreELEC.tv will get support too?

**Comment by Raybuntu** [comment]
This issue tracker is for my builds. If you have trouble with official LibreELEC builds please use the official channels. I never tested HifiShield+ with official LibreELEC.
