### ISSUE TITLE
Update not working

### ISSUE THREAD

**Issue by tuxedo0801** [Raybuntu/LibreELEC.tv#39]
I'm currently running KODI raybuntu version rb-eia8 9.0 kernel 3.14.29 (Kodi 18.0-ALPHA1 Git:a5f1e85)) on an wetek play 2 (on SD card, not internal NAND) and want to update to the latest version. Runs fine so far (except some smaller bugs)

I downloaded todays latest image (like I did multiple times before), copied the image to /storage/.update via SCP, rebootet kodi and got this message:

![img_20171103_125531_hdr](https://user-images.githubusercontent.com/2862906/32372896-14745e78-c097-11e7-854a-69d1ff69aaf5.jpg)

What's wrong? How do I fix this? Do I really need to re-write the whole SD card?

**Comment by Raybuntu** [comment]
Please download the .tar file. Update is broken using img.gz. Update with tar is also much faster

**Comment by Raybuntu** [comment]
btw: https://github.com/Raybuntu/LibreELEC.tv/releases/tag/rb-leia14

**Comment by tuxedo0801** [comment]
Thanks a lot. works now. updating to leia14
