### ISSUE TITLE
3D files didnt show up properly

### ISSUE THREAD

**Issue by 146fhm** [Raybuntu/LibreELEC.tv#4]
Hi, I'm using LibreELEC-WeTek_Play_2.arm-8.0-rb-krypton1.

I played 3d file with 2d mode and It's showing up but not properly as its suppose but like the image files i attached. I have even tried with libreelec krypton 7.95.3 beta. It is shown properly at first or two seconds, after that its stuttering and freeze. Its a known bug?

Thanks.

![dsc_1381](https://cloud.githubusercontent.com/assets/25708472/23101770/85f280ce-f6d6-11e6-963a-c3c87d791789.JPG)
![dsc_1386](https://cloud.githubusercontent.com/assets/25708472/23101769/85f05e34-f6d6-11e6-94a4-f0e62dfd2820.JPG)

**Comment by Raybuntu** [comment]
Is it working with 7.95.3? I can not support 3D since I have no 3d TV. Afaik it is not fixed in Kodi yet.

**Comment by 146fhm** [comment]
No, we dont need a 3d TV to watch in monoscopic/2d mode. Thank you by the way. Will wait for kodi fix. :-)

**Comment by Raybuntu** [comment]
OK, I still don't have video files. If you are seeing same issue with 7.95.3 then report it to official LE project. And attach a sample.
