### ISSUE TITLE
Building TexturePacker failed on Ubuntu 17.10

### ISSUE THREAD

**Issue by Gizmo-Ger** [Raybuntu/LibreELEC.tv#40]
I ran into the next issue: Building failed on TexturePacker.

[9/10] Building CXX object CMakeFiles/TexturePacker.dir/src/decoder/GifHelper.o
FAILED: CMakeFiles/TexturePacker.dir/src/decoder/GifHelper.o 
/home/shs/LibreELEC.tv/build.LibreELEC-Odroid_C2.arm-9.0-devel/toolchain/bin/host-g++    -I/home/shs/LibreELEC.tv/build.LibreELEC-Odroid_C2.arm-9.0-devel/toolchain/include -I/home/shs/LibreELEC.tv/build.LibreELEC-Odroid_C2.arm-9.0-devel/kodi-055f6ee/tools/depends/native/TexturePacker/../../../../xbmc -I/home/shs/LibreELEC.tv/build.LibreELEC-Odroid_C2.arm-9.0-devel/kodi-055f6ee/tools/depends/native/TexturePacker/../../../../lib -I/home/shs/LibreELEC.tv/build.LibreELEC-Odroid_C2.arm-9.0-devel/kodi-055f6ee/tools/depends/native/TexturePacker/src -I/home/shs/LibreELEC.tv/build.LibreELEC-Odroid_C2.arm-9.0-devel/kodi-055f6ee/tools/depends/native/TexturePacker/src/decoder -O2 -Wall -pipe -I/home/shs/LibreELEC.tv/build.LibreELEC-Odroid_C2.arm-9.0-devel/toolchain/include -Wno-format-security -std=c++11 -DTARGET_POSIX -DTARGET_LINUX -D_LINUX -I/home/shs/LibreELEC.tv/build.LibreELEC-Odroid_C2.arm-9.0-devel/kodi-055f6ee/xbmc/linux -MD -MT CMakeFiles/TexturePacker.dir/src/decoder/GifHelper.o -MF CMakeFiles/TexturePacker.dir/src/decoder/GifHelper.o.d -o CMakeFiles/TexturePacker.dir/src/decoder/GifHelper.o -c /home/shs/LibreELEC.tv/build.LibreELEC-Odroid_C2.arm-9.0-devel/kodi-055f6ee/tools/depends/native/TexturePacker/src/decoder/GifHelper.cpp
In file included from /usr/include/c++/7/cstdlib:75:0,
                 from /usr/include/c++/7/ext/string_conversions.h:41,
                 from /usr/include/c++/7/bits/basic_string.h:6349,
                 from /usr/include/c++/7/string:52,
                 from /home/shs/LibreELEC.tv/build.LibreELEC-Odroid_C2.arm-9.0-devel/kodi-055f6ee/tools/depends/native/TexturePacker/src/decoder/GifHelper.h:45,
                 from /home/shs/LibreELEC.tv/build.LibreELEC-Odroid_C2.arm-9.0-devel/kodi-055f6ee/tools/depends/native/TexturePacker/src/decoder/GifHelper.cpp:21:
/usr/include/stdlib.h:443:14: error: declaration of 'void* reallocarray(void*, size_t, size_t) throw ()' has a different exception specifier
 extern void *reallocarray (void *__ptr, size_t __nmemb, size_t __size)
              ^~~~~~~~~~~~
In file included from /home/shs/LibreELEC.tv/build.LibreELEC-Odroid_C2.arm-9.0-devel/kodi-055f6ee/tools/depends/native/TexturePacker/src/decoder/GifHelper.h:23:0,
                 from /home/shs/LibreELEC.tv/build.LibreELEC-Odroid_C2.arm-9.0-devel/kodi-055f6ee/tools/depends/native/TexturePacker/src/decoder/GifHelper.cpp:21:
/home/shs/LibreELEC.tv/build.LibreELEC-Odroid_C2.arm-9.0-devel/toolchain/include/gif_lib.h:248:1: note: from previous declaration 'void* reallocarray(void*, size_t, size_t)'
 reallocarray(void *optr, size_t nmemb, size_t size);
 ^~~~~~~~~~~~
ninja: build stopped: subcommand failed.
Makefile:9: die Regel für Ziel „release“ scheiterte
make: *** [release] Fehler 1

**Comment by Raybuntu** [comment]
This is a known issue in Ubuntu 17.10. It's a clash between giflib and glibc.

**Comment by Gizmo-Ger** [comment]
OK. Thank you for the info

**Comment by Raybuntu** [comment]
I will see if I find a solution.

**Comment by Raybuntu** [comment]
This should be fixed now in my Leia branch
