### ISSUE TITLE
IPv6

### ISSUE THREAD

**Issue by rubdos** [Raybuntu/LibreELEC.tv#41]
Hello,

I'm migrating from the LibreELEC official image to yours, and while I have enabled IPv6 in settings, I'm not getting an IPv6 address.

Is this something you changed? The official images (8.2.0) do work.

**Comment by Raybuntu** [comment]
Can you provide logs?

**Comment by rubdos** [comment]
What kind of logs do you want? I don't know what kind of network system is used on libreelec :/
I didn't see anything unusual in dmesg, but I'll paste it nonetheless when I have access again.

**Comment by rubdos** [comment]
[Here's dmesg](https://paste.fedoraproject.org/paste/o7PZuPL5aoWpJAHVv0V3Ng)

**Comment by rubdos** [comment]
Is this a randomly close because lack of activity, or is this actually fixed?

**Comment by Raybuntu** [comment]
Sorry for not explaining. I don't have ipv6 so I don't know how to fix it.

**Comment by rubdos** [comment]
Would you mind guiding me somehow to see what I should check? I asked what logs to provide, but didn't hear anything beyond that. I'd love to have this fixed somehow, some day :-)

**Comment by Raybuntu** [comment]
First of all it would be good to know what device you are using. dmesg log is fine. You log file seems down.

**Comment by rubdos** [comment]
Odroid C2 (with HiFi shield). If you did releases since Nov 18, I probably didn't update. Here's [dmesg](https://pastebin.com/xzbhjvxf) of one instance. There are four of them, clean install, all no ipv6. With the official C2 image, there's ipv6, but other stuff is pretty unstable.

Let me know if you require anything else.

**Comment by Raybuntu** [comment]
I've made some updates to LE settings addon Network since then. I don't know if it's fixed but it might be worth a try updating. I'm also about to release a new build. But be aware that there are some issues due to the new Kernel and also I'm going to update boot.ini automatically and a downgrade won't be that easy.

**Comment by rubdos** [comment]
I'll give it a try next time when I have physical access. Currently remote. I'll report back here if it isn't fixed after the new build you are about to release. I have *no fear*™ of downgrading since I have Ansible scripts to do the tedious config work ;-)

Thanks for you support.

**Comment by rubdos** [comment]
Hmm, now I wonder, will your new release be Krypton?

**Comment by Raybuntu** [comment]
No I no longer support Krypton.

**Comment by rubdos** [comment]
Oh, roger that. So I'll have to upgrade to Leia then, which is kind of troublesome; that means there's no LibreELEC build that's got a "released"/stable version of Kodi for the C2 that does support the HiFiShields.

**Comment by Raybuntu** [comment]
I think you HiFi Shield should work with official as well. There is nothing special I add. I'm also moving everything I have to official since I'm more involved with the official LibreELEC project now. My next build will be almost vanilla LE master since I've upstreamed all features I added to my builds.

**Comment by rubdos** [comment]
I'll need to do more testing that; thanks for all of your feedback! :-)
