### ISSUE TITLE
Questions about ROCK64 Install

### ISSUE THREAD

**Issue by NickyNice** [Raybuntu/LibreELEC.tv#42]
Hello,
  
I got a ROCK64 recently and am trying to install this build of LibreELEC on it. I'm curious what file to download though and how to install it, since I don't see any instructions anywhere.

Should I use the Odroid C2 img.gz file and write it to my SD card using the LibreELEC SD creator tool?
**Edit: I think I'm seeing now that I need to download the latest Leia "Pre Release" build is this correct?**

Or should I use some other method? Also, what is the tar file for? I'm guessing that after getting it on the SD card its mostly plug and play right?

I'm sorry if this isn't a good place to ask this, I wasn't sure where else to post. Thank you.

**Comment by Raybuntu** [comment]
This tracker is for issues only 
https://forum.libreelec.tv/thread/4248-libreelec-krypton-leia-agile-build-for-odroid-c2-rock64-wetek-hub-wetek-play2/
