### ISSUE TITLE
Adding USB gadget MASS STORAGE kernel module.

### ISSUE THREAD

**Issue by mkmt** [Raybuntu/LibreELEC.tv#44]
Please try to compile kernel with USB_GADGET and USB_MASS_STORAGE as a module.

Then it is possible to configure LE to use its OTG port as a mass storage for TV, so it can be used as a proxy between NAS server and TV for live TV recording without need to connect HDD.

**Comment by danielfmo** [comment]
Hi,

USB_GADGET is already set. USB_MASS_STORAGE must be enabled:
I created the PR:
https://github.com/Raybuntu/LibreELEC.tv/pull/45

**Comment by Raybuntu** [comment]
Odroid_C2 moved from a Project to a device under Amlogic project. PR needs to be rebased.
