### ISSUE TITLE
Jerky video from HDHomerun device

### ISSUE THREAD

**Issue by bmentink** [Raybuntu/LibreELEC.tv#46]
Hi, I am not sure  why this is happening as other videos seem to play ok

**Comment by Raybuntu** [comment]
Please provide more info

**Comment by bmentink** [comment]
Not sure what I can provide. I just installed the HDHomerun plugin and tried a few channels .... is there some log file I can provide?

**Comment by Raybuntu** [comment]
I'm sorry if it came out rude. This was not my intention.
I'm doing a lot of builds over several Kodi release and different devices. For starters it's good to provide kodi logs. Otherwise it's hard for me to guess.

**Comment by bmentink** [comment]
No problem, if you can just tell me what log is most useful (there are many) and I will attach.

**Comment by Raybuntu** [comment]
I would suggest to use my latest build.
I will probably publish a new build tomorrow.
For most recent onces:
https://forum.pine64.org/showthread.php?tid=5130

**Comment by bmentink** [comment]
Thanks for the new build.
I have tried the latest rb-leia19 build and same issues, very jerky un-watchable playback om both mpeg2 and HD sources ..

**Comment by bmentink** [comment]
Also, Emby plugin does not work at all in this build, I guess that will come? ;)
(Installed plugin from http://kodi.emby.media)

**Comment by Raybuntu** [comment]
Ahh ok. Currently there is no hardware encoding for mpeg2. So HD mpeg2 is a bit much for Rock64 cpu.
