### ISSUE TITLE
System crashes/locks up whem Emby plugin fetching data off server

### ISSUE THREAD

**Issue by bmentink** [Raybuntu/LibreELEC.tv#47]
Hi, I have installed the Emby plugin for Kodi and it seems to lock things up when it is fetching all the library data on startup. Sometimes it just locks things up solid and you have to reboot, other times it resets the box. I will try to see if there are any relevant log files around ..

After a few reboots and when all the data is fetched, it seems to work ok, although 1080p content is jerky

**Comment by Raybuntu** [comment]
You did not provide any info what device but even that there is no by plugin available for Kodi 18 yet. So your experimental probably Community driven Addon could be unstable.

**Comment by bmentink** [comment]
Sorry Rock64 device. I thought that was what this build was targeting. So this build it not implementing hardware accel for the Rock64 device? I was trying it out based on that information (from the Pine64 community)

**Comment by Raybuntu** [comment]
And what version?

**Comment by bmentink** [comment]
I presume you mean what version of your code?
I downloaded latest from here: https://github.com/Raybuntu/LibreELEC.tv/releases/download/rb-krypton18/LibreELEC-ROCK64.arm-8.2-rb-krypton18.img.gz

**Comment by Raybuntu** [comment]
Ok this is not my latest but at least I have to admit that for 8.2 there is a Emby plugin. I'm just focusing on 9.0 now.

**Comment by bmentink** [comment]
Oh, I stupidly assumed the link on Pine's site linked to your latest ... I shouldn't assume .. :)
So can you send me a link to your latest then, so I can do testing on that?

Cheers

**Comment by Raybuntu** [comment]
Posted on the other issue
