### ISSUE TITLE
Rock64:rb-leia19 HDHomerun jerky video

### ISSUE THREAD

**Issue by bmentink** [Raybuntu/LibreELEC.tv#48]
Hi,
I think you misunderstood. Only SD in our country is MPEG2, for HD the format is  h.264.
Both formats are jerky and buffering .... it looks more like the data is not being delivered fast enough ..

**Comment by Raybuntu** [comment]
Please don't open new issues. You can reopen closed ones. As I said before I no longer support Krypton. I have tested pvr hts which works fine for me.
Please provide kodi debug log preferably with Leia.
