### ISSUE TITLE
Mac Address and Boot Process

### ISSUE THREAD

**Issue by dynek** [Raybuntu/LibreELEC.tv#5]
Hello @Raybuntu,

First of all, many thanks for the great work!

Not sure which way should be preferred to talk problems but I thought GitHub would be the right place.

I'm using an Odroid C2 and updated from a previous version of wrxtasy to rb-krypton5 earlier today and rb-krypton6 as it just came out few hours ago and I see two odd things with both:
- MAC Address changes upon each boot - Random addresses are being used
- If the TV is already turned on I see the LibreElec startup logo but not the second one saying "Kodi Krypton". Screen remains black but an IP address is requested behind so the system is booting. Now if TV is turned off while I power on the Odroid C2, it works as expected: both logo show up one after the other and I can use the system.

Would you happen to have any idea?

Thank you!

**Comment by Raybuntu** [comment]
What wrxtasy version did you use? Might be required to do a clean install. Did you vhange the boot.ini?

**Comment by dynek** [comment]
As far as I remember it was LibreELEC 7.0.2 - Kodi Jarvis 16.1.

I did not touch boot.ini at all so far.

**Comment by Raybuntu** [comment]
I think the update system does not update boot.ini and those 2 versions are not entirely compatible.
I'm not quite sure about it though.

**Comment by dynek** [comment]
You were right - Replacing boot.ini fixed both issues.

**Comment by Raybuntu** [comment]
Thanks for confirming. Enjoy.
