### ISSUE TITLE
missing dvb drivers or/and firmware on Leia 21 on C2

### ISSUE THREAD

**Issue by feuille2lune** [Raybuntu/LibreELEC.tv#50]
Since rb-leia21 release, it seem that ma dvb adapter is not correctly detected anymore, it worked well on rb-leia20. 

there are my lsusb : 
LibreELEC:~# lsusb 
Bus 001 Device 004: ID 0d8c:013c C-Media Electronics, Inc. CM108 Audio Controller
**Bus 001 Device 025: ID 07ca:1835 AVerMedia Technologies, Inc.** 
Bus 001 Device 002: ID 05e3:0610 Genesys Logic, Inc. 4-port hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

Tvheadend server 4.2 doesn't see it in web-interface and when I try through KODI to lanch a TV channel, it says "no adapter available"

Which logs do you need to investigate, how can I generate them ?

**Comment by Raybuntu** [comment]
It's semi supported if you already enabled crazycat driver addons and it's still not there then it's no longer supported.

**Comment by feuille2lune** [comment]
I checked in deep configurations and crazycat drivers addon had been disabled. I don't know why, but I enabled it and it works now ! Thanks for this information,I'll sleep smarter tonight.
