### ISSUE TITLE
rock64 : 4k HDR on 1080p. Forced RGB output?

### ISSUE THREAD

**Issue by bigbossyakusa** [Raybuntu/LibreELEC.tv#51]
Hi, 
I have an error about the color when i play a 4k with HDR on my FullHD TV sony. The color is whashed.
Apparently, it is because the output pass on YUV when there are HDR content in the file. The solution found on other forum is to forced the signal output on RGB instead of YUV.
But i have not found how to do this on Rock64.

Thanks in advance and sorry for my english and if it is not posted on the good forum

**Comment by Raybuntu** [comment]
Currently not possible on Rock64. But maybe in the future.
