### ISSUE TITLE
Rock64:rb-leia21: USB HDD standby - can sdparm be added to the distro?

### ISSUE THREAD

**Issue by zarusz** [Raybuntu/LibreELEC.tv#53]
Hello,

First of all thank you for the work on this distribution for ROCK64.

I have few HDD attached via the USB interface to my Rock64. I would want to  be able spin down all disks after some inactivity. Two disks spin down fine using the pre-installed `hdparm`. However, my 3rd disk (Segate) requires `sdparm`  to spin it down (this disk has SCSI interface). As I understand for LibreELEC packages cannot be installed by the user.

Can the `sdparm` be added to the distribution as well with your next release?

Right now, my workaround is to run a docker debian container in privileged mode to be able to install `sdparm` and spin down the disk:

```
sdparm --flexible -6 -l --save --set SCT=54000 /dev/sdb
sdparm --flexible -6 -l --save --set STANDBY=1 /dev/sdb
```
(54000 * 0.1s) = 1.5h

Docker:
```
docker run --rm --privileged --device=/dev/sda:/dev/sda -it arm64v8/debian

apt-get update
apt-get install sdparm -y
```

Version:
```
Linux Rock64 4.4.103 #1 SMP Fri Dec 22 08:22:26 CET 2017 aarch64 GNU/Linux
```

**Comment by Raybuntu** [comment]
I'm only building packages that are included in official LE. Please make a feature request for sdparm on LE forum.

**Comment by zarusz** [comment]
Thanks, I've created a feature request [here](https://forum.libreelec.tv/thread/11526-usb-hdd-standby-can-sdparm-be-added-to-the-distro/).
