### ISSUE TITLE
Kodi on Rock64 Black Screen after first video

### ISSUE THREAD

**Issue by chad3** [Raybuntu/LibreELEC.tv#54]
Just started using LibreELEC with Kodi on a ROCK64.  I set up YouTube addon.  Things seem to work.
After playing a YouTube video, the screen is set black and the Kodi desktop does not display.  I used a ssh login to verify that Linux was still running.

My guess is that the video is set black (off) in a way that Kodi doesn't undo when it re-displays its GUI.  I'm new to Kodi, LibreELEC but not new to Linux.  Any suggestions for how to debug this would be appreciated, including references to documentation.

**Comment by Raybuntu** [comment]
Rockchip Kodi Video support is still Work in progress. The issue you discribe is already known and it's being worked on.

**Comment by chad3** [comment]
Thanks for the reply.  Is there a detailed problem description I can learn from?
