### ISSUE TITLE
ODROID C2, free, Jerky on heavy mkv 1080p

### ISSUE THREAD

**Issue by t3uch1** [Raybuntu/LibreELEC.tv#55]
Hello
I allow myself to contact you because I use your distribution leia 22 and when I look at large file 1080p h264 I have little jerk or little frost at some scene
I tested with your last distribution under Kypton and no worries
under leia 22 I manage to reduce these freeze by deactivating acceleration h264 but I do not think that it is a good solution
have you ever experienced the worries?
thank you

**Comment by Raybuntu** [comment]
No but we have a new Kernel since leia22 and Frameskips are already known

**Comment by t3uch1** [comment]
Hello,
Thanks for your help,
What versuin I have used to no longer have this problem? 19? 20? or wait 23?
Thanks
