### ISSUE TITLE
Rock64: rb-leia22 no retroarch

### ISSUE THREAD

**Issue by Rebebel** [Raybuntu/LibreELEC.tv#56]
Hi,

When I launch retroarch or advanced launcher,
Kodi ask me if I want to quit Kodi for the app,I say "yes"

Then It goes back to the boot page of libreelec (before kodi logo).

Is there a way to make retroarch working on Rock64 ? (it is working on android for Rock64 but with this android os there is no way to activate bluetooth dongle)

PS : was not working on krypton

**Comment by Raybuntu** [comment]
I have no idea about retroarch. I've only tested Kodi's internal Retroplayer and it is working. I suggest you use Lakka.

**Comment by Rebebel** [comment]
Ok I see I realize that retroplayer is normally merge with kodi.....

But....

I have no "games" category in my kodi Home ( I just update to rb-leia22 from rb-krypton via .update tar) where i should launch retro games

**Comment by Raybuntu** [comment]
I posted at the pine64 forum and at the LE forum that you need to input a KONAMI code to enable the Games menu in kodi. That's how Kodi wants it to be.

**Comment by Rebebel** [comment]
oh !
thank you to give me a piece of your time.

I dindn't know about KONAMI code. I'll check it.

great work!
