### ISSUE TITLE
Rock64: rb-leia 22 dualshock 3

### ISSUE THREAD

**Issue by Rebebel** [Raybuntu/LibreELEC.tv#57]
Me again....

I need a gamepad controller to input KONAMI code in kodi to have the games section appear in home menu,

but
I don't reach to make my dualshock 3 ps3 game controller to connect with my rock64, even via usbcable or via bluetooth. Bluetooth is activated (my bt dongle with led on) but i don't see the ps3 controller. Via usb cable....nothing happend.
I try also to download and install kodi drivers for playstation gamepad but don'work.

any suggestion?

**Comment by Raybuntu** [comment]
User a usb keyboard to input the KONAMI code.

**Comment by Rebebel** [comment]
ok 

but no way to have ps3 gamepad as kodi controller?

**Comment by Raybuntu** [comment]
I'm not sure. I heard it is working on Amlogic but I have no ps3 gamepad so I can't support it. Once we have official Rockchip support in LibreELEC maybe some other developer with one can fix it.
