### ISSUE TITLE
Green Line displayed at bottom of HEVC Video

### ISSUE THREAD

**Issue by alexus1211** [Raybuntu/LibreELEC.tv#6]
Please check this:

https://forum.libreelec.tv/thread-7621.html

**Comment by Raybuntu** [comment]
Please provide a debug log with ONLY video component specific logging using my latest (rb-krypton10) community build. Please do not crosspost your issue everywhere. You reported it for official LE. This is my personal bugtracker for my community builds. For reference repost your sample video here too.
