### ISSUE TITLE
Can't go further than v21 on Rock64+eMMC

### ISSUE THREAD

**Issue by tedr56** [Raybuntu/LibreELEC.tv#61]
Hi
I'm discovering the LibreElec install/upgrade process.
However, I can't make it work further than v21 on Rock64
I tried with direct flash img or upgrade with v22 Tar from .update on v21, both freeze the board at start.
No screen, and leds stay on.

I don't know how to get further info on the issue here, since nothing happen.

On the bright side, v21 works fine.
Thanks for the hard work.

**Comment by tedr56** [comment]
I forgot to mention that I'm using the eMmc module.

**Comment by tedr56** [comment]
Tried on a sdcard.
Seems to be the same.

**Comment by tedr56** [comment]
v22 works on SdCard
v23 throw kernel panics

**Comment by Raybuntu** [comment]
Leia23 is extremely unstable. I don't recommend using it.
I have no emmc so I can't support it.

**Comment by tedr56** [comment]
I'm trying to find what changed between 21 and 22
But Rockchip Project was not merged yet.
What project did you use to build for Rock64?

**Comment by Raybuntu** [comment]
It's either Leia-rk4 branch (until leia22) or rockchip branch.

**Comment by tedr56** [comment]
From this discussion
https://github.com/ayufan-rock64/linux-kernel/commit/95368b4b832d932f75a1813a056805b84af9cff6

ayufan brings back emmc clock to dts
https://github.com/ayufan-rock64/linux-kernel/commit/95368b4b832d932f75a1813a056805b84af9cff6

I have no idea how to include this in patch file though.

There is some other things missing too.
https://gist.github.com/tedr56/2353c7ab7fd9b68c9e3662abafddb5a9/revisions
