### ISSUE TITLE
Unable to open media in rar files (WeTek Play 2)

### ISSUE THREAD

**Issue by andres-v2** [Raybuntu/LibreELEC.tv#62]
Upgraded from 8.2.3 to 9.0 (LibreELEC-WeTek_Play_2.arm-rb-leia23.tar) following instructions in http://www.wetekforums.com/v/index.php?p=/discussion/29237/libreelec-8-community-play2-64bit-kernel-32bit-libs/p1

Everything works fine, except opening media files in rar archives. Error message "Playback failed - One or more items failed to play"
Log messages:
NOTICE: VideoPlayer::OpenFile: rar://[omitted]
NOTICE: Creating InputStream
WARNING: Create - unsupported protocol(rar) in rar://[omitted]
WARNING: CreateLoader - unsupported protocol(rar) in rar://[omitted]
ERROR: CVideoPlayer::OpenInputStream - error opening [rar://[omitted]
NOTICE: CVideoPlayer::OnExit()

**Comment by Raybuntu** [comment]
Have you tried installing vfs.rar addon from my repo?

**Comment by andres-v2** [comment]
Was missing that one, fixed the issue. Thanks a lot!
