### ISSUE TITLE
Rock64 leia23 build - no hardware acceleration on video playback?

### ISSUE THREAD

**Issue by mth** [Raybuntu/LibreELEC.tv#64]
The leia23 build for rock64 seems to be pretty much broken.

* Got kernel panic on first boot after resize (guessing it was random)
* Could not go to configure static IP in the UI (this worked for me on leia22 and previous versions)
* The HDMI output seems to occasionally shut down after stopping video playback. This affected also leia22 and I could restore the display by killing kodi process so it restarted.
* The hardware acceleration seems to be not working.

Tested following videos:

http://jell.yfish.us/media/jellyfish-10-mbps-hd-hevc-10bit.mkv - no output (the UI was shown, but video was just black)
http://www.libde265.org/hevc-bitstreams/bbb-1920x1080-cfg06.mkv - total slide show
https://www.youtube.com/watch?v=Neos6gICi6I with youtube-dl into webm
1920x1080 vp9/opus 37MiB - slide show

All of those have ok playback with leia21 and leia22.

Btw, the leia21 build works great on the Rock64. :)

**Comment by TiloWiklund** [comment]
I'm also getting kernel panics with leia23 (leia22 works), so I don't think yours was random.

**Comment by Raybuntu** [comment]
yes it's known
