### ISSUE TITLE
Change url of kernel-firmware

### ISSUE THREAD

**Issue by z-e-r-o** [Raybuntu/LibreELEC.tv#8]
Change URL in LibreELEC.tv/packages/linux-firmware/kernel-firmware/package.mk [agile]  from
http://git.kernel.org/cgit/linux/kernel/git/firmware/linux-firmware.git/snapshot/$PKG_VERSION.tar.xz
to
http://git.kernel.org/cgit/linux/kernel/git/firmware/linux-firmware.git/snapshot/$PKG_VERSION.tar.gz
GZ instead of XZ, otherwise make runs into error.

**Comment by Raybuntu** [comment]
Its already fixed upstream https://github.com/Raybuntu/LibreELEC.tv/commit/05f583137012f959fd25e38422fbbaa4986cf5f8
BTW if you are building for intel use official LE repo. I do mostly work for amlogic (C2, WH, WP2)
