### ISSUE TITLE
compatible with dvbsky s960

### ISSUE THREAD

**Issue by horstepipe** [Raybuntu/LibreELEC.tv#9]
hey Ray
are your builds supposed to be compatible with the DVBSky S960? 
I just installed the rb-krypton11 release, unfortunately tvheadend doesn't find my dvbsky.

**Comment by Raybuntu** [comment]
My next build will include media build drivers:
Here are previews for WH and C2:
https://mega.nz/#F!N4wy2QYL!wJN6oZ0pRRoXQtMs8bQ0tA
WP2 does not work yet.
